Neste notebook, vamos codificar Redes Neurais de forma manual para tentar entender intuitivamente como elas são implementadas na prática.

# Sumário

- [Exemplo 1](#Exemplo-1)
- [Exemplo 2](#Exemplo-2)
- [O que precisamos para implementar uma Rede Neural?](#O-que-precisamos-para-implementar-uma-Rede-Neural?)
- [Referências](#Referências)

# Imports e Configurações

In [1]:
import numpy as np

# Exemplo 1

<img src="./images/backprop_example_1.png">

In [2]:
# implementando a função de ativação sigmoid
def sigmoid(x, derivative=False):
    # Função de ativação sigmoid
    if derivative:
        # Calcula a derivada da função sigmoid em relação a x
        # y é o resultado da função sigmoid aplicada a x
        # Retorna a derivada da função sigmoid aplicada a x
        y = sigmoid(x)
        return y * (1 - y)
        
    # Retorna o resultado da função sigmoid aplicada a x
    return 1 / (1 + np.exp(-x))

In [3]:
# inicializando entradas
x = np.array([[0.05, 0.10]])
y = np.array([[0.01, 0.99]])

# inicializando pesos e bias
w1 = np.array([[0.15, 0.20], [0.25, 0.30]]) # array com 2x2
b1 = np.array([[0.35]])

# pesos e bias da segunda camada
w2 = np.array([[0.40, 0.45], [0.50, 0.55]]) # array 2x2
b2 = np.array([[0.60]])

learning_rate = 0.5

In [4]:
# camada feed foward
for i in range(1):
    # primeira camada
    inp1 = np.dot(x, w1.T) + b1
    h1 = sigmoid(inp1)
    
    # segunda camada
    inp2 = np.dot(h1, w2.T) + b2
    out = sigmoid(inp2)
    
    # custo
    cost = 0.5 * np.sum((y - out) ** 2)
    
    # backpropagation
    dout = -(y - out) # derivada do custo (antes usado como 1 nos exemplos)
    
    # segunda camada
    dinp2 = sigmoid(inp2, derivative=True) * dout
    dh1 = np.dot(dinp2, w2)
    dw2 = np.dot(dinp2.T, h1)
    db2 = 1 * dinp2.sum(axis=0, keepdims=True) # multiplicando mantendo dimensao para manter como um vetor 2d
    
    # primeira camada
    dinp1 = sigmoid(inp1, derivative = True) * dh1
    dx = np.dot(dinp1, w1)
    dw1 = np.dot(dinp1.T, x)
    db1 = 1 * dinp1.sum(axis=0, keepdims = True)

    # atualizando os pesos e bias
    w2 = w2 - learning_rate * dw2
    b2 = b2 - learning_rate * db2
    w1 = w1 - learning_rate * dw1
    b1 = b1 - learning_rate * db1

# Exemplo 2

In [5]:
def linear(x, derivative=False):
    return np.ones_like(x) if derivative else x

def relu(x, derivative=False):
    if derivative:
        x = np.where(x <= 0, 0, 1)
    return np.maximum(0, x)

def softmax(x, y_oh=None, derivative=False):
    if derivative:
        y_pred = softmax(x)
        k = np.nonzero(y_pred * y_oh)
        pk = y_pred[k]
        y_pred[k] = pk * (1.0 - pk)
        return y_pred
    
    exp = np.exp(x)    
    return exp / np.sum(exp, axis=1, keepdims=True) # mantendo as dimensoes para somar os valores linha a linha mantendo as dimensoes

def neg_log_likelihood(y_oh, y_pred, derivative=False):
    k = np.nonzero(y_pred * y_oh)
    pk = y_pred[k]
    if derivative:
        y_pred[k] = (-1.0 / pk)
        return y_pred
    return np.mean(-np.log(pk))

def softmax_neg_log_likelihood(y_oh, y_pred, derivative=False):
    y_softmax = softmax(y_pred)
    if derivative:
        k = np.nonzero(y_pred * y_oh)
        dlog = neg_log_likelihood(y_oh, y_softmax, derivative=True)
        dsoftmax = softmax(y_pred, y_oh, derivative=True)
        y_softmax[k] = dlog[k] * dsoftmax[k]
        return y_softmax / y_softmax.shape[0]
    return neg_log_likelihood(y_oh, y_softmax)

# import numpy as np

# def linear(x, derivative=False):
#     # Retorna uma matriz de mesma forma que x com todos os elementos iguais a 1
#     if derivative:
#         return np.ones_like(x)
#     else:
#         return x

# def relu(x, derivative=False):
#     # Função de ativação ReLU (Rectified Linear Unit)
#     if derivative:
#         # Retorna uma matriz de mesma forma que x com valores 0 onde x é menor
#         #ou igual a 0 e 1 onde x é maior que 0
#         return np.where(x <= 0, 0, 1)
#     else:
#         # Retorna uma matriz de mesma forma que x com valores 0 onde x é menor que
#         #0 e x onde x é maior ou igual a 0
#         return np.maximum(0, x)

# def softmax(x, y_oh=None, derivative=False):
#     # Função de ativação Softmax
#     if derivative:
#         # Calcula a derivada da função softmax em relação a x
#         # y_oh é a codificação one-hot do vetor de rótulos verdadeiros y
#         # Retorna uma matriz com as derivadas parciais da função softmax em relação a cada elemento de x
#         y_pred = softmax(x)
#         k = np.nonzero(y_pred * y_oh)
#         pk = y_pred[k]
#         y_pred[k] = pk * (1.0 - pk)
#         return y_pred
    
#     exp = np.exp(x)    
#     # Retorna uma matriz com as probabilidades resultantes da função softmax aplicada a cada linha de x
#     return exp / np.sum(exp, axis=1, keepdims=True)

# def neg_log_likelihood(y_oh, y_pred, derivative=False):
#     # Calcula a perda negativa do logaritmo de verossimilhança
#     # y_oh é a codificação one-hot do vetor de rótulos verdadeiros y
#     # y_pred é o vetor de probabilidades previstas pelo modelo
#     k = np.nonzero(y_pred * y_oh)
#     pk = y_pred[k]
#     if derivative:
#         # Calcula a derivada da perda em relação a y_pred
#         # Retorna uma matriz com as derivadas parciais da perda em relação a cada elemento de y_pred
#         y_pred[k] = (-1.0 / pk)
#         return y_pred
#     # Retorna a média da perda negativa do logaritmo de verossimilhança
#     return np.mean(-np.log(pk))

# def softmax_neg_log_likelihood(y_oh, y_pred, derivative=False):
#     # Calcula a perda negativa do logaritmo de verossimilhança combinada com a função softmax
#     # y_oh é a codificação one-hot do vetor de rótulos verdadeiros y
#     # y_pred é o vetor de probabilidades previstas pelo modelo
#     y_softmax = softmax(y_pred)
#     if derivative:
#         # Calcula a derivada da perda combinada em relação a y_pred
#         # Retorna uma matriz com as derivadas parciais da perda combinada em 
#         #relação a cada elemento de y_pred
#         k = np.nonzero(y_pred * y_oh)
#         dlog = neg_log_likelihood(y_oh, y_softmax, derivative=True)
#         dsoftmax = softmax(y_pred, y_oh, derivative=True)
#         y_softmax[k] = dlog[k] * dsoftmax[k]
#     # Retorna a perda negativa do logaritmo
#     return y_softmax / y_softmax.shape[0]

In [6]:
x = np.array([[0.1, 0.2, 0.7]])
y = np.array([[1, 0, 0]])

# Pesos e bias para a primeira camada
w1 = np.array([[0.1, 0.2, 0.3], [0.3, 0.2, 0.7], [0.4, 0.3, 0.9]])
b1 = np.ones((1,3))

# Pesos e bias para a segunda camada
w2 = np.array([[0.2, 0.3, 0.5], [0.3, 0.5, 0.7], [0.6, 0.4, 0.8]])
b2 = np.ones((1,3))

# Pesos e bias para a terceira camada
w3 = np.array([[0.1, 0.4, 0.8], [0.3, 0.7, 0.2], [0.5, 0.2, 0.9]])
b3 = np.ones((1,3))

learning_rate = 0.01

# Loop de treinamento
for i in range(301):
    # Feedforward
    
    # 1a camada
    inp1 = np.dot(x, w1.T) + b1
    h1 = relu(inp1)
    
    # 2a camada
    inp2 = np.dot(h1, w2.T) + b2
    h2 = sigmoid(inp2)
    
    # 3a camada
    inp3 = np.dot(h2, w3.T) + b3
    out = linear(inp3)
    
    cost = softmax_neg_log_likelihood(y, out)
    
    # Backpropagation
    
    # Cálculo do gradiente da perda em relação à saída da última camada
    dout = softmax_neg_log_likelihood(y, out, derivative=True)
    
    # 3a camada
    dinp3 = linear(inp3, derivative=True) * dout
    dh2 = np.dot(dinp3, w3)
    dw3 = np.dot(dinp3.T, h2)
    db3 = 1.0 * dinp3.sum(axis=0, keepdims=True)
    
    # 2a camada
    dinp2 = sigmoid(inp2, derivative=True) * dh2
    dh1 = np.dot(dinp2, w2)
    dw2 = np.dot(dinp2.T, h1)
    db2 = 1.0 * dinp2.sum(axis=0, keepdims=True)
    
    # 1a camada
    dinp1 = relu(inp1, derivative=True) * dh1
    dx = np.dot(dinp1, w1)
    dw1 = np.dot(dinp1.T, x)
    db1 = 1.0 * dinp1.sum(axis=0, keepdims=True)
    
    # atualizando pesos e bias
    w3 = w3 - learning_rate * dw3
    b3 = b3 - learning_rate * db3
    
    w2 = w2 - learning_rate * dw2
    b2 = b2 - learning_rate * db2
    
    w1 = w1 - learning_rate * dw1
    b1 = b1 - learning_rate * db1
    
    
    # verificando as saídas
    if i % 30 == 0:
        cost = softmax_neg_log_likelihood(y, out)
        print(cost)
        
for w in [w1, w2, w3]:
    print(w)

1.1674456052871238
0.6079795820435693
0.36558760028370507
0.2494345154899926
0.18547915491555542
0.14614614804167672
0.1199051550833629
0.10131084011234358
0.08751844300750028
0.07691720650783256
0.06853445083252654
[[0.10083595 0.2016719  0.30585165]
 [0.30086971 0.20173942 0.70608796]
 [0.40145052 0.30290104 0.91015363]]
[[0.20544723 0.30673159 0.50749567]
 [0.30994562 0.5123005  0.71366784]
 [0.61065514 0.41317913 0.81464085]]
[[ 0.66465527  0.98758148  1.39393956]
 [ 0.05020341  0.44006253 -0.06274803]
 [ 0.18514132 -0.12764401  0.56880846]]


# O que precisamos para implementar uma Rede Neural?

# Referências

- [Neural Network from Scratch](https://beckernick.github.io/neural-network-scratch/)
- [Backpropagation Algorithm](https://theclevermachine.wordpress.com/tag/backpropagation-algorithm/)
- [Back-Propagation is very simple. Who made it Complicated ?](https://becominghuman.ai/back-propagation-is-very-simple-who-made-it-complicated-97b794c97e5c)
- [A Step by Step Backpropagation Example](https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/)
- [Understanding softmax and the negative log-likelihood](https://ljvmiranda921.github.io/notebook/2017/08/13/softmax-and-the-negative-log-likelihood/)